### ISSUE TITLE
Missing class methods

### ISSUE THREAD

**Issue by perfaram** [walkman8196/DPCIManager#1]
Hi !
First of all, thanks to you for continuing support in this project, that's nice !
Unfortunately, whenever I try to compile (Mavericks, AppleClang-600.0.57, xCode 6.2), I get 4 'missing class selector', in Hardware.m, for [[NSApp delegate] X], where X is `report`, `setReport` (twice), and `pcis`.
Do you have any idea ??
Thx !

**Comment by walkman8196** [comment]
Only started to understand, while is not present

**Comment by perfaram** [comment]
OK

**Comment by perfaram** [comment]
I understood : [NSApp delegate] actually references the AppDelegate (of DPCIManager). For some reason, xCode doesn't understand that. To force it to reconsider, I had to clean the products and change some projects build settings (i.e. switch it to 10.9, then back to 10.10). Poof, it works. Silly xCode.

**Comment by walkman8196** [comment]
may you pull requests with changes without errors?

**Comment by perfaram** [comment]
I changed nothing in source code, but I''ll try to see whether something changed in .xcodeproj. If so, I'll make a PR !

Date: Tue, 14 Apr 2015 01:53:54 -0700
